import java.util.ArrayList;

public class Map {
	Room northwesternForest=new Room();
	Room southwesternForest=new Room();
	Room northeasternForest=new Room();
	Room southeasternForest=new Room();
	Room westernCanyon=new Room();
	Room easternCanyon=new Room();
	Room altar=new Room();
	static Room startAltar=new Room();
	Room nsRoadOne=new Room();
	Room nsRoadTwo=new Room();
	Room easternField=new Room();
	Room westernField=new Room();
	Room crossroads=new Room();
	Room ewRoadOne=new Room();
	Room ewRoadTwo=new Room();
	Room bridge=new Room();
	Room river=new Room();
	Room commonQuarter=new Room();
	Room merchantQuarter=new Room();
	Room magicQuarter=new Room();
	Room nobleQuarter=new Room();
	Room forestTempleEntry=new Room();
	Room canyonTempleEntry=new Room();
	Room waterTempleEntry=new Room();
	Room swamp=new Room();
	Room plague=new Room();
	Room guardHouse=new Room();
	Food berries= new Food("berries", 10, 10, 5);
	Food squirrel= new Food("squirrel", 10, 20, 10);
	Food deer= new Food("deer", 20, 50,25);
	Item box= new Item("locked box", 0, 0);
	ArrayList<Item> northWesternForestItemsList= new ArrayList<Item>();
	ArrayList<Item> southWesternForestItemsList= new ArrayList<Item>();
	ArrayList<Item> northEasternForestItemsList= new ArrayList<Item>();
	ArrayList<Item> southEasternForestItemsList= new ArrayList<Item>();
	ArrayList<Item> westernCanyonList= new ArrayList<Item>();
	ArrayList<Item> easternCanyonList= new ArrayList<Item>();
	ArrayList<Item> altarList= new ArrayList<Item>();
	ArrayList<Item> nsRoadOneList= new ArrayList<Item>();
	ArrayList<Item> nsRoadTwoList= new ArrayList<Item>();
	ArrayList<Item> easternFieldList= new ArrayList<Item>();
	ArrayList<Item> westernFieldList= new ArrayList<Item>();
	ArrayList<Item> crossroadsList= new ArrayList<Item>();
	ArrayList<Item> ewRoadOneList= new ArrayList<Item>();
	ArrayList<Item> ewRoadTwoList= new ArrayList<Item>();
	ArrayList<Item> bridgeList= new ArrayList<Item>();
	ArrayList<Item> riverList= new ArrayList<Item>();
	ArrayList<Item> commonQuarterList= new ArrayList<Item>();
	ArrayList<Item> merchantQuarterList= new ArrayList<Item>();
	ArrayList<Item> magicQuarterList= new ArrayList<Item>();
	ArrayList<Item> nobleQuarterList= new ArrayList<Item>();
	ArrayList<Item> forestTempleEntryList= new ArrayList<Item>();
	ArrayList<Item> canyonTempleEntryList= new ArrayList<Item>();
	ArrayList<Item> waterTempleEntryList= new ArrayList<Item>();
	ArrayList<Monster> northWesternForestMonsterList= new ArrayList<Monster>();
	ArrayList<Monster> southWesternForestMonsterList= new ArrayList<Monster>();
	ArrayList<Monster> northEasternForestMonsterList= new ArrayList<Monster>();
	ArrayList<Monster> southEasternForestMonsterList= new ArrayList<Monster>();
	ArrayList<Monster> westernCanyonMonsterList= new ArrayList<Monster>();
	ArrayList<Monster> easternCanyonMonsterList= new ArrayList<Monster>();
	ArrayList<Monster> altarMonsterList= new ArrayList<Monster>();
	ArrayList<Monster> nsRoadOneMonsterList= new ArrayList<Monster>();
	ArrayList<Monster> nsRoadTwoMonsterList= new ArrayList<Monster>();
	ArrayList<Monster> easternFieldMonsterList= new ArrayList<Monster>();
	ArrayList<Monster> westernFieldMonsterList= new ArrayList<Monster>();
	ArrayList<Monster> crossroadsMonsterList= new ArrayList<Monster>();
	ArrayList<Monster> ewRoadOneMonsterList= new ArrayList<Monster>();
	ArrayList<Monster> ewRoadTwoMonsterList= new ArrayList<Monster>();
	ArrayList<Monster> bridgeMonsterList= new ArrayList<Monster>();
	ArrayList<Monster> riverMonsterList= new ArrayList<Monster>();
	ArrayList<Monster> commonQuarterMonsterList= new ArrayList<Monster>();
	ArrayList<Monster> merchantQuarterMonsterList= new ArrayList<Monster>();
	ArrayList<Monster> magicQuarterMonsterList= new ArrayList<Monster>();
	ArrayList<Monster> nobleQuarterMonsterList= new ArrayList<Monster>();
	ArrayList<Monster> forestTempleEntryMonsterList= new ArrayList<Monster>();
	ArrayList<Monster> canyonTempleEntryMonsterList= new ArrayList<Monster>();
	ArrayList<Monster> waterTempleEntryMonsterList= new ArrayList<Monster>();
	void setUp() {
		northwesternForest.setFields("You are in a pine forest you can see the light filtering through the canopy. To the west you see a imposing door carved into a immense redwood tree, and to the north there are fields and fields of corn. There is only more forest to the south, and to the east lies a road.", westernField, nsRoadOne, southwesternForest, forestTempleEntry, northWesternForestItemsList, northWesternForestMonsterList);
		northWesternForestItemsList.add(berries);
		northWesternForestItemsList.add(squirrel);
		northWesternForestItemsList.add(deer);
		northWesternForestItemsList.add(box);
		southwesternForest.setFields("You are in a pine forest. You can see the light filtering through the canopy.", northwesternForest, altar, westernCanyon, forestTempleEntry, southWesternForestItemsList, southWesternForestMonsterList);
		southWesternForestItemsList.add(berries);
		southWesternForestItemsList.add(squirrel);
		southWesternForestItemsList.add(deer);
		northeasternForest.setFields("Forest", easternField, forestTempleEntry, southeasternForest, nsRoadOne, northEasternForestItemsList, northEasternForestMonsterList);
		northEasternForestItemsList.add(berries);
		northEasternForestItemsList.add(squirrel);
		northEasternForestItemsList.add(deer);
		southeasternForest.setFields("Forest", northeasternForest, forestTempleEntry, easternCanyon, altar, southEasternForestItemsList, southEasternForestMonsterList);
		southEasternForestItemsList.add(berries);
		southEasternForestItemsList.add(squirrel);
		southEasternForestItemsList.add(deer);
		westernCanyon.setFields("Canyon", southwesternForest, canyonTempleEntry, null, easternCanyon, westernCanyonList, westernCanyonMonsterList);
		easternCanyon.setFields("Canyon", southeasternForest, westernCanyon, null, canyonTempleEntry, easternCanyonList, easternCanyonMonsterList);
		altar.setFields("In front of you there is a small marble platform with a raised marble slab. On the slab there appear to be 4 indents as if once 4 small objects had been there. Engraved in the stone it reads: \"Here is the true resting spot of the elemental artifacts.\"", nsRoadOne, southeasternForest, null, southwesternForest, altarList, altarMonsterList);
		startAltar.setFields("In front of you there is a small marble platform with a raised marble slab. On the slab there appear to be 4 indents as if once 4 small objects had been there. Engraved in the stone it reads: \"Here is the true resting spot of the elemental artifacts.\"", nsRoadOne, southeasternForest, null, southwesternForest, altarList, altarMonsterList);
		nsRoadOne.setFields("North/South King's Road", nsRoadTwo, northeasternForest, altar, northwesternForest, nsRoadOneList, nsRoadOneMonsterList);
		nsRoadTwo.setFields("North/South King's Road", crossroads, easternField, nsRoadOne, westernField, nsRoadTwoList,nsRoadTwoMonsterList);
		easternField.setFields("Field", null, westernField, northeasternForest, nsRoadTwo, easternFieldList, easternFieldMonsterList);
		westernField.setFields("Field", null, nsRoadTwo, northwesternForest, easternField, westernFieldList, westernFieldMonsterList);
		crossroads.setFields("King's Cross", commonQuarter, ewRoadTwo, nsRoadTwo, ewRoadOne, crossroadsList, crossroadsMonsterList);
		ewRoadOne.setFields("East/West King's Road", null, crossroads, null, crossroads, ewRoadOneList, ewRoadOneMonsterList);
		ewRoadTwo.setFields("East/West King's Road", null, swamp, null, crossroads, ewRoadTwoList,ewRoadTwoMonsterList);
		bridge.setFields("River Bridge", null, ewRoadOne, river, plague, bridgeList, bridgeMonsterList);
		river.setFields("River", bridge, null, waterTempleEntry, null, riverList, riverMonsterList);
		commonQuarter.setFields("Common Quarter", nobleQuarter, magicQuarter, crossroads, merchantQuarter, commonQuarterList, commonQuarterMonsterList);
		merchantQuarter.setFields("Merchant's Quarter", nobleQuarter, magicQuarter, commonQuarter, null, merchantQuarterList, merchantQuarterMonsterList);
		magicQuarter.setFields("Arcane Quarter", nobleQuarter, null, commonQuarter, magicQuarter, magicQuarterList, magicQuarterMonsterList);
		nobleQuarter.setFields("Noble Quarter", guardHouse, magicQuarter, commonQuarter, merchantQuarter, nobleQuarterList, nobleQuarterMonsterList);
		forestTempleEntry.setFields("Forest Temple", null, northwesternForest, null, northeasternForest, forestTempleEntryList, forestTempleEntryMonsterList);
		canyonTempleEntry.setFields("Canyon Temple", null, easternCanyon, null, westernCanyon, canyonTempleEntryList, canyonTempleEntryMonsterList);
		waterTempleEntry.setFields("Water Temple", river, null, null, null, waterTempleEntryList, waterTempleEntryMonsterList);
	}
	static Room getAltar() {
		return startAltar;
	}
}
